#!/bin/bash
# ==============================================================================
# clang-tidy Script
# ==============================================================================
# This script runs clang-tidy against the project sources using the
# compile_commands.json generated by CMake.
#
# Usage: ./ci/clang-tidy.sh
# ==============================================================================

set -e

# ==============================================================================
# Configuration
# ==============================================================================
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BUILD_DIR="$PROJECT_ROOT/build"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# ==============================================================================
# Helper Functions
# ==============================================================================
print_header() {
    echo ""
    echo -e "${BLUE}========================================${NC}"
    echo -e "${BLUE}  $1${NC}"
    echo -e "${BLUE}========================================${NC}"
    echo ""
}

print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

error_exit() {
    print_error "$1"
    exit 1
}

# ==============================================================================
# Main Script
# ==============================================================================
print_header "clang-tidy Script"

if [ ! -d "$BUILD_DIR" ]; then
    print_warning "Build directory not found. Creating and configuring..."
    mkdir -p "$BUILD_DIR" || error_exit "Failed to create build directory"
    cd "$BUILD_DIR" || error_exit "Failed to enter build directory"
    cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON "$PROJECT_ROOT" \
        || error_exit "CMake configuration failed"
else
    cd "$BUILD_DIR" || error_exit "Failed to enter build directory"
fi

if [ ! -f "$BUILD_DIR/compile_commands.json" ]; then
    print_info "Generating compile_commands.json..."
    cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON "$PROJECT_ROOT" \
        || error_exit "CMake configuration failed"
fi

print_info "Running clang-tidy..."

FILES=$(find "$PROJECT_ROOT/src" "$PROJECT_ROOT/include" -type f \
    \( -name "*.c" -o -name "*.h" \))

if [ -z "$FILES" ]; then
    print_info "No source files found to analyze"
    exit 0
fi

echo "$FILES" | xargs clang-tidy -p "$BUILD_DIR" \
    || error_exit "clang-tidy reported issues"

print_success "clang-tidy completed successfully"
